#!/usr/bin/env python3
"""Regenerate index.html and the filter block in style.css from the JSON.

photos.json and filters.json are the only files you edit by hand. Everything
derived from them is written here, and the script refuses to write at all if
the data is inconsistent, so a broken page cannot reach the repo.

    python3 build.py --check    report only, write nothing
    python3 build.py            write index.html and style.css

SITE env var overrides the directory, which is how the tests drive it.
"""

import hashlib
import html
import json
import os
import re
import sys
from datetime import datetime, timezone

try:
    from PIL import Image
except ImportError:          # the laptop does not need Pillow to publish
    Image = None

SITE = os.environ.get("SITE", os.path.dirname(os.path.abspath(__file__)))

REQUIRED = ("slug", "file", "designation", "name", "class", "grade",
            "instrument", "optics", "site", "filter", "captured",
            "published", "note", "alt", "w", "h")

GRADES = ("nominal", "degraded")

TITLE = "Long Range Sensors"
TAGLINE = ("Robotic telescopes on three continents, pointed at things that "
           "were already old when the light left them. Some of these came out. "
           "The rest are here anyway, with the fault written on the label.")


class BuildError(Exception):
    pass


def load(name):
    with open(os.path.join(SITE, name), encoding="utf-8") as fh:
        return json.load(fh)


def digest(name):
    with open(os.path.join(SITE, name), "rb") as fh:
        return hashlib.sha1(fh.read()).hexdigest()[:8]


def stardate(when=None):
    when = when or datetime.now(timezone.utc)
    epoch = datetime(2026, 1, 1, tzinfo=timezone.utc)
    return 47000 + (when - epoch).total_seconds() / 86400.0 * 2.7379


def validate(photos, filters):
    """Every check here has cost a real debugging session somewhere."""
    problems = []
    keys = {f["key"] for f in filters}
    seen = set()
    last_published = None

    if not photos:
        problems.append("photos.json is empty")

    for i, p in enumerate(photos):
        where = p.get("slug") or "index %d" % i

        for field in REQUIRED:
            if not p.get(field):
                problems.append("%s: missing %s" % (where, field))

        if p.get("slug") in seen:
            problems.append("%s: duplicate slug" % where)
        seen.add(p.get("slug"))

        if p.get("class") and p["class"] not in keys:
            problems.append("%s: class '%s' has no filter in filters.json"
                            % (where, p["class"]))

        if p.get("grade") not in GRADES:
            problems.append("%s: grade must be one of %s" % (where, ", ".join(GRADES)))
        elif p["grade"] == "degraded" and not p.get("fault"):
            problems.append("%s: degraded records must name a fault" % where)
        elif p["grade"] == "nominal" and p.get("fault"):
            problems.append("%s: nominal records must not carry a fault" % where)

        img_path = os.path.join(SITE, "images", p.get("file") or "")
        if p.get("file") and not os.path.exists(img_path):
            problems.append("%s: images/%s is not in the repo" % (where, p["file"]))
        elif p.get("w") and p.get("h") and Image is not None:
            # Declared dimensions reserve the layout box before the image
            # arrives. Wrong ones are worse than none, so check them against
            # the file wherever Pillow is installed.
            try:
                with Image.open(img_path) as im:
                    if im.size != (p["w"], p["h"]):
                        problems.append("%s: declared %dx%d but the file is %dx%d"
                                        % (where, p["w"], p["h"], im.size[0], im.size[1]))
            except Exception as exc:
                problems.append("%s: could not read images/%s (%s)" % (where, p["file"], exc))

        if p.get("alt", "").strip().lower().startswith(("image of", "photo of", "picture of")):
            problems.append("%s: alt text should describe, not announce" % where)

        pub = p.get("published")
        if pub:
            if last_published and pub > last_published:
                problems.append("%s: photos.json must be sorted newest published first" % where)
            last_published = pub

    used = {p.get("class") for p in photos}
    for f in filters:
        if f["key"] not in used:
            problems.append("filter '%s' matches nothing" % f["key"])

    return problems


def filter_css(filters):
    lines = ["/* filters:start */",
             "/* Generated by build.py. Hide everything once any box is checked,",
             "   then restore each checked class. Separate rules mean the",
             "   selection unions rather than intersects. */",
             "body:has(.fbox:checked) .plate { display: none; }"]
    for f in filters:
        lines.append("body:has(#f-%s:checked) .plate.c-%s { display: flex; }"
                     % (f["key"], f["key"]))
    lines.append("/* filters:end */")
    return "\n".join(lines)


def e(text):
    return html.escape(str(text), quote=True)


def utc_label(stamp):
    """2026-09-04T06:03Z -> 2026-09-04 06:03 UTC"""
    m = re.match(r"(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2})Z?$", stamp)
    return "%s %s UTC" % (m.group(1), m.group(2)) if m else stamp


def render_plate(p, i, total):
    fault = ('<span class="status degraded">Degraded &middot; %s</span>' % e(p["fault"])
             if p["grade"] == "degraded"
             else '<span class="status nominal">Nominal</span>')
    return """      <li class="plate c-{cls}" id="p-{slug}">
        <a class="shot" href="#v-{slug}" aria-label="Open {name} full screen">
          <span class="idx">{idx} / {total}</span>
          <img src="images/{file}" alt="{alt}" width="{w}" height="{h}" loading="lazy" decoding="async">
        </a>
        <div class="readout">
          <div class="name">
            <h2>{name}</h2>
            <span class="desig">{desig}</span>
          </div>
          {fault}
          <dl class="specs">
            <dt>Instrument</dt><dd>{instrument} &middot; {optics}</dd>
            <dt>Site</dt><dd>{site}</dd>
            <dt>Filter</dt><dd>{filter}</dd>
            <dt>Captured</dt><dd>{captured}</dd>
          </dl>
          <p class="note">{note}</p>
        </div>
      </li>
""".format(cls=e(p["class"]), slug=e(p["slug"]), idx="%02d" % i, total="%02d" % total,
           file=e(p["file"]), alt=e(p["alt"]), name=e(p["name"]), w=p["w"], h=p["h"],
           desig=e(p["designation"]), fault=fault, instrument=e(p["instrument"]),
           optics=e(p["optics"]), site=e(p["site"]), filter=e(p["filter"]),
           captured=e(utc_label(p["captured"])), note=e(p["note"]))


def render_viewer(p, i, total, prev_slug, next_slug):
    return """  <div class="viewer" id="v-{slug}" role="dialog" aria-label="{name}, full screen">
    <div class="vhead">
      <h2>{name}</h2>
      <span class="desig">{desig}</span>
      <span class="spacer"></span>
      <a class="vbtn close" href="#p-{slug}">Close</a>
    </div>
    <div class="vstage"><img src="images/{file}" alt="{alt}" loading="lazy" decoding="async"></div>
    <div class="vfoot">
      <a class="vbtn prev" href="#v-{prev}" aria-label="Previous record">&lsaquo;</a>
      <a class="vbtn next" href="#v-{next}" aria-label="Next record">&rsaquo;</a>
      <span class="vcount">{idx} / {total}</span>
      <p class="vnote">{note}</p>
    </div>
  </div>
""".format(slug=e(p["slug"]), name=e(p["name"]), desig=e(p["designation"]),
           file=e(p["file"]), alt=e(p["alt"]), prev=e(prev_slug), next=e(next_slug),
           idx="%02d" % i, total="%02d" % total, note=e(p["note"]))


def render(photos, filters, css_v, js_v):
    total = len(photos)
    plates = "".join(render_plate(p, i + 1, total) for i, p in enumerate(photos))

    viewers = ""
    for i, p in enumerate(photos):
        prev_slug = photos[(i - 1) % total]["slug"]
        next_slug = photos[(i + 1) % total]["slug"]
        viewers += render_viewer(p, i + 1, total, prev_slug, next_slug)

    pills = ""
    for f in filters:
        pills += ('        <input type="checkbox" class="fbox" id="f-%s">\n'
                  '        <label class="btn %s" for="f-%s">%s<span class="code">%s</span></label>\n'
                  % (e(f["key"]), e(f["colour"]), e(f["key"]), e(f["label"]), e(f["code"])))

    nominal = sum(1 for p in photos if p["grade"] == "nominal")

    return """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="Robotic telescope captures, logged with the fault written on the label.">
<meta name="theme-color" content="#000000">
<meta name="color-scheme" content="dark">
<link rel="stylesheet" href="style.css?v={css_v}">
</head>
<body>
<div class="frame">

  <header class="head">
    <div class="elbow"></div>
    <div class="bar">
      <h1>{title_uc}</h1>
      <span class="seg seg-a"></span>
      <span class="seg seg-b"></span>
      <span class="stardate" id="stardate">Stardate {sd}</span>
    </div>
    <div class="cap"></div>
  </header>

  <div class="shell">
    <nav class="rail" aria-label="Filter records by class">
      <div class="rail-lead"></div>
      <p class="rail-heading">Class</p>
      <form class="filters">
{pills}        <button type="reset" class="btn reset">All<span class="code">47-0000</span></button>
      </form>
      <div class="rail-tail"></div>
    </nav>

    <main class="well">
      <p class="brief">{tagline}</p>
      <p class="count">{total} records logged &middot; {nominal} nominal &middot; {degraded} degraded</p>
      <ol class="plates">
{plates}      </ol>
    </main>
  </div>

  <footer class="foot">
    <div class="elbow"></div>
    <div class="bar">
      <span>Captured with <a href="https://slooh.com">Slooh</a></span>
      <span>Watermarks left intact</span>
      <a href="#top">Top</a>
    </div>
    <div class="cap"></div>
  </footer>

</div>

{viewers}
<script src="app.js?v={js_v}"></script>
</body>
</html>
""".format(title=e(TITLE), title_uc=e(TITLE), css_v=css_v, js_v=js_v,
           sd="%.1f" % stardate(), tagline=e(TAGLINE), total=total,
           nominal=nominal, degraded=total - nominal, pills=pills,
           plates=plates, viewers=viewers)


def main():
    check_only = "--check" in sys.argv

    photos = load("photos.json")
    filters = load("filters.json")

    problems = validate(photos, filters)
    if problems:
        print("REFUSING TO WRITE. %d problem(s):" % len(problems))
        for p in problems:
            print("  - " + p)
        return 1

    css_path = os.path.join(SITE, "style.css")
    with open(css_path, encoding="utf-8") as fh:
        css = fh.read()
    new_css = re.sub(r"/\* filters:start \*/.*?/\* filters:end \*/",
                     lambda _: filter_css(filters), css, flags=re.S)
    if new_css is None or "filters:start" not in new_css:
        raise BuildError("filter markers missing from style.css")

    css_changed = new_css != css
    if css_changed and not check_only:
        with open(css_path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(new_css)

    # Hash after the filter block is settled, so the query string tracks what
    # actually ships. This is what retires the stale-stylesheet bug.
    css_v = hashlib.sha1(new_css.encode("utf-8")).hexdigest()[:8]
    js_v = digest("app.js")

    page = render(photos, filters, css_v, js_v)
    index_path = os.path.join(SITE, "index.html")
    old = ""
    if os.path.exists(index_path):
        with open(index_path, encoding="utf-8") as fh:
            old = fh.read()

    # The stardate moves every second, so compare with it masked out.
    mask = lambda s: re.sub(r"Stardate [\d.]+", "Stardate X", s)
    index_changed = mask(page) != mask(old)

    print("%d records, %d filters, %d nominal, %d degraded"
          % (len(photos), len(filters), sum(1 for p in photos if p["grade"] == "nominal"),
             sum(1 for p in photos if p["grade"] == "degraded")))
    print("style.css would change: %s" % css_changed)
    print("index.html would change: %s" % index_changed)

    if check_only:
        return 0

    if index_changed or not old:
        with open(index_path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(page)
        print("wrote index.html (style.css?v=%s, app.js?v=%s)" % (css_v, js_v))
    else:
        print("nothing to do")
    return 0


if __name__ == "__main__":
    sys.exit(main())
